version: '3'
services:
  redis:
    image: redis
    networks:
      - redis
  mongo:
    image: mongo
    networks:
      - mongo
  activemq:
    image: rmohr/activemq
    networks:
      - activemq
  farmer:
    build: farmer/.
    ports:
      - "8000:8000"
    networks:
      - backend
      - redis
      - mongo
      - activemq
  factory:
    build: factory/.
    ports:
      - "8001:8001"
    networks:
      - backend
  snackbar:
    build: snackbar/.
    ports:
      - "8002:8002"
    networks:
      - backend
networks:
  backend:
    driver: bridge
  redis:
    driver: bridge
  mongo:
    driver: bridge
  activemq:
    driver: bridge
