version: '3'
services:
  redis:
    image: redis
    networks:
      - backend
  farmer:
    build: farmer/.
    ports:
      - "8000:8000"
    networks:
      - backend
  factory:
    build: factory/.
    ports:
      - "8001:8001"
    networks:
      - backend
  snackbar:
    build: snackbar/.
    ports:
      - "8002:8002"
    networks:
      - backend
networks:
  backend:
    driver: bridge
